language: java

services:
  - mysql

addons:
  firefox: 83.0

env:
  global:
    - MOZ_HEADLESS=1

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS quality;"

before_script:
  - mysql -e "USE quality;
        DROP TABLE IF EXISTS students;
        CREATE TABLE students(
          id varchar(50) NOT NULL,
          name varchar(30) DEFAULT NULL,
          email varchar(100) DEFAULT NULL,
          age int DEFAULT NULL,
          average float DEFAULT NULL,
          PRIMARY KEY (id)
        );"
  - mysql -e "USE quality; INSERT INTO students(id,name,email,age,average) values('331754','Alan Zuniga','00331754@anahuac.mx',22,7.8);"
  - mysql -e "USE quality; INSERT INTO students(id,name,email,age,average) values('0335486','Fredy Fuzman','00335486@anahuac.mx',21,8.2);"
  - mysql -e "USE quality; INSERT INTO students(id,name,email,age,average) values('336174','Jose Rasgado','00336174@anahuac.mx',22,8.8);"
  - mysql -e "USE quality; SELECT * FROM students;"

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver