language: java

services:
  - mysql

addons:
  firefox: 83.0
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

env:
  global:
    - MOZ_HEADLESS=1
    - _FORCE_LOGS=1
    - DEVICE=android
    - MOCHA_TIMEOUT=360000
    - RECURSIVE=
    - START_EMU=1
    - ANDROID_EMU_NAME=test
    - ANDROID_EMU_TARGET=android-21
    - ANDROID_EMU_ABI=armeabi-v7a
    - CC=gcc-4.9 CXX=g++-4.9
  matrix:
    - TEST=unit RECURSIVE=--recursive START_EMU=0
    - TEST=functional
    - TEST=functional/bootstrap
    - TEST=functional/commands/keyboard
    - TEST=functional/commands
    - TEST=functional/commands/basic
    - TEST=functional/commands/find
    - TEST=functional/commands/touch

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS quality;"

before_script:
  - mysql -e "USE quality;
        DROP TABLE IF EXISTS students;
        CREATE TABLE students(
          id int NOT NULL,
          name varchar(30) DEFAULT NULL,
          email varchar(100) DEFAULT NULL,
          age int DEFAULT NULL,
          average float DEFAULT NULL,
          PRIMARY KEY (id)
        )"

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

  # node stuff
  - nvm install 10
  - npm install appium-test-support # get the travis emu scripts

  # android stuff
  - android list sdk --extended --no-ui --all
  - android list targets
  - $(npm bin)/android-emu-travis-pre

  # npm stuff
  - npm install

  # make sure emulator started
  - $(npm bin)/android-emu-travis-post
  - sleep 30
  - adb shell input keyevent 82 &