language: java

services:
  - mysql

addons:
  firefox: 83.0

cache:

before_install:
  - mysql 

before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS quality;"
  - mysql -e "USE quality;
	DROP TABLE IF EXISTS `students`;
	CREATE TABLE `students` (
	  `id` int NOT NULL,
	  `name` varchar(30) DEFAULT NULL,
	  `email` varchar(100) DEFAULT NULL,
	  `age` int DEFAULT NULL,
	  `average` float DEFAULT NULL,
	  PRIMARY KEY (`id`)
	)"