language: java

addons:
  firefox: 83.0

cache:
  npm: true
  yarn: true
  directories:
    - node_modules

before_script:
  - npm install -g firefoxdriver
  - npm install -g selenium-side-runner
  - yarn add firefoxdriver
  - yarn add selenium-side-runner